import { useState } from 'react'
import { ArrowDown, ArrowRight, Award, BookOpen, Check, ChevronDown, Clock3, Download, ExternalLink, FileText, Gift, GraduationCap, Heart, Layers, Lightbulb, Lock, Menu, Monitor, Pencil, Play, Printer, Rocket, Search, ShieldCheck, Sparkles, Star, Tablet, Target, Users, X, Zap } from 'lucide-react'

const CHECKOUT_URL = 'https://seu-checkout-aqui.com'
const goCheckout = () => { window.location.href = CHECKOUT_URL }

const categories = [
  ['📖', 'Alfabetização', 'Letras, sílabas, consciência fonológica e leitura.'],
  ['🔢', 'Matemática', 'Números, operações, sequência e raciocínio.'],
  ['✏️', 'Português', 'Escrita, interpretação e atividades de linguagem.'],
  ['🎨', 'Educação Infantil', 'Coordenação, cores, formas e descobertas.'],
  ['🎲', 'Jogos pedagógicos', 'Opções divertidas para aprender brincando.'],
]
const gallery = [
  ['ALFABETIZAÇÃO', 'Vamos formar palavras?', 'A B C', 'purple'],
  ['MATEMÁTICA', 'Complete a sequência', '1 2 3 4 5', 'yellow'],
  ['PORTUGUÊS', 'Leia e responda', 'Era uma vez...', 'blue'],
  ['COORDENAÇÃO', 'Trace e descubra', '〰 〰 〰', 'coral'],
  ['JOGO PEDAGÓGICO', 'Bingo das letras', 'B I N G O', 'green'],
  ['RACIOCÍNIO', 'Qual é o próximo?', '★ ○ ★ ○', 'lavender'],
]
const faqItems = [
  ['O material é físico?', 'Não. O Kit é 100% digital. Você recebe os arquivos para acessar pelo celular, tablet ou computador e imprimir quando quiser.'],
  ['Como recebo o acesso?', 'Após a confirmação do pagamento, você recebe as instruções de acesso no e-mail informado na compra.'],
  ['Quando recebo o acesso?', 'O acesso é liberado de forma rápida após a confirmação do pagamento.'],
  ['Preciso ter impressora?', 'Não necessariamente. Você pode salvar os arquivos, consultar no celular ou imprimir em uma gráfica quando precisar.'],
  ['Posso imprimir quantas vezes precisar?', 'Sim. O material fica salvo para você consultar e imprimir novamente sempre que precisar.'],
  ['Posso utilizar com meus alunos?', 'Sim. O Kit foi pensado para apoiar a rotina de professoras, educadores e famílias.'],
  ['Existe garantia?', 'Sim. Você conta com 7 dias de garantia para conhecer o material.'],
]

function Button({ children, secondary = false }: { children: React.ReactNode; secondary?: boolean }) {
  return <button onClick={goCheckout} className={`group inline-flex min-h-14 items-center justify-center gap-3 rounded-2xl px-7 text-sm font-extrabold uppercase tracking-wide shadow-lg transition hover:-translate-y-1 hover:shadow-xl ${secondary ? 'border-2 border-white/30 bg-white/10 text-white hover:bg-white/20' : 'bg-coral text-white shadow-coral/25 hover:bg-[#e75a3d]'}`}>{children}<ArrowRight size={18} className="transition group-hover:translate-x-1" /></button>
}

function Header() {
  const [open, setOpen] = useState(false)
  return <>
    <div className="bg-navy px-4 py-2 text-center text-[10px] font-bold uppercase tracking-[.14em] text-white sm:text-xs">📚 Atividades prontas para usar <span className="mx-2 text-sun">•</span> 📥 Acesso digital <span className="mx-2 text-sun">•</span> ✅ 7 dias de garantia</div>
    <header className="sticky top-0 z-40 border-b border-ink/5 bg-cream/90 backdrop-blur-md">
      <div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><a href="#inicio" className="font-display text-lg font-extrabold text-navy">Kit <span className="text-purple">Professora</span><br className="sm:hidden" /> Sem Tempo™</a><nav className="hidden items-center gap-7 text-sm font-bold text-ink/70 md:flex"><a href="#kit">O que vem</a><a href="#galeria">Veja por dentro</a><a href="#duvidas">Dúvidas</a><Button>Quero meu kit</Button></nav><button onClick={() => setOpen(!open)} className="rounded-xl p-2 md:hidden" aria-label="Menu">{open ? <X /> : <Menu />}</button></div>
      {open && <div className="absolute left-0 right-0 border-b bg-cream px-5 py-5 shadow-lg md:hidden"><div className="flex flex-col gap-5 font-bold"><a href="#kit" onClick={() => setOpen(false)}>O que vem</a><a href="#galeria" onClick={() => setOpen(false)}>Veja por dentro</a><a href="#duvidas" onClick={() => setOpen(false)}>Dúvidas</a><Button>Quero meu kit</Button></div></div>}
    </header>
  </>
}

function Mockup() {
  return <div className="relative mx-auto h-[420px] max-w-[390px] animate-float sm:h-[480px]"><div className="absolute left-3 top-16 h-64 w-44 -rotate-12 rounded-lg bg-white p-3 shadow-2xl sm:left-8 sm:h-72 sm:w-52"><div className="h-full rounded border-2 border-purple/20 p-3"><div className="mb-5 h-3 w-20 rounded bg-purple/30"/><div className="grid grid-cols-3 gap-2">{Array.from({length:9}).map((_,i)=><div key={i} className="aspect-square rounded bg-purple/10"/>)}</div><div className="mt-5 h-2 w-full rounded bg-ink/10"/><div className="mt-2 h-2 w-3/4 rounded bg-ink/10"/></div></div><div className="absolute right-0 top-12 h-72 w-52 rotate-6 rounded-lg bg-white p-3 shadow-2xl sm:right-3 sm:h-80 sm:w-60"><div className="flex h-full flex-col rounded border-2 border-sun/50 p-4"><div className="mb-5 flex items-center justify-between"><span className="rounded-full bg-sun px-3 py-1 text-[9px] font-black">ATIVIDADE</span><Star size={20} className="fill-sun text-sun"/></div><div className="font-display text-2xl font-extrabold leading-tight text-navy">KIT<br/><span className="text-purple">PROFESSORA</span><br/>SEM TEMPO™</div><div className="mt-auto rounded-xl bg-navy p-3 text-center text-[9px] font-bold text-white">ABRA • ESCOLHA • IMPRIMA • USE</div></div></div><div className="absolute bottom-8 left-8 right-5 rounded-3xl bg-navy p-5 text-white shadow-soft sm:bottom-4 sm:left-14 sm:right-8"><div className="mb-2 flex items-center gap-2 text-sun"><Sparkles size={18}/><span className="text-[10px] font-black uppercase tracking-widest">Sua biblioteca pronta</span></div><p className="font-display text-xl font-extrabold">Tudo salvo para o dia em que você precisar.</p></div><div className="absolute left-0 top-5 rounded-full bg-sun px-4 py-2 text-xs font-black text-ink shadow-lg">+ 100 materiais</div></div>
}

function Hero() { return <section id="inicio" className="overflow-hidden bg-cream"><div className="mx-auto grid max-w-6xl items-center gap-8 px-5 pb-14 pt-12 lg:grid-cols-[1fr_1fr] lg:gap-16 lg:pb-24 lg:pt-20"><div className="animate-fade-up"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-purple/20 bg-purple/10 px-4 py-2 text-xs font-extrabold uppercase tracking-wide text-purple"><Sparkles size={15}/> Sua gaveta de emergência pedagógica</div><h1 className="max-w-xl font-display text-4xl font-extrabold leading-[1.08] text-ink sm:text-6xl">Precisou de uma <span className="text-purple">atividade</span> e <span className="text-coral">não tem tempo</span> para preparar?</h1><p className="mt-6 max-w-lg text-base leading-7 text-ink/65 sm:text-lg">Tenha um acervo de atividades pedagógicas prontas para escolher, imprimir e usar sempre que precisar — sem perder horas procurando material na internet.</p><div className="mt-7 flex flex-wrap gap-2">{['📖 Alfabetização','🔢 Matemática','✏️ Português','🎨 Ed. Infantil','🎲 Jogos'].map(x=><span key={x} className="rounded-full bg-white px-3 py-2 text-xs font-bold text-ink shadow-sm">{x}</span>)}</div><div className="my-8 flex flex-wrap items-center gap-2 text-xs font-black uppercase text-navy sm:text-sm"><span className="rounded-lg bg-sun/50 px-3 py-2">ABRA</span><ArrowRight size={15}/><span className="rounded-lg bg-sun/50 px-3 py-2">ESCOLHA</span><ArrowRight size={15}/><span className="rounded-lg bg-sun/50 px-3 py-2">IMPRIMA</span><ArrowRight size={15}/><span className="rounded-lg bg-sun/50 px-3 py-2">USE</span></div><div className="flex flex-col items-start gap-4 sm:flex-row sm:items-center"><Button>Quero meu kit agora</Button><div><div className="font-display text-2xl font-extrabold text-navy">R$ 27,00</div><div className="text-xs font-semibold text-ink/50">pagamento único</div></div></div><div className="mt-5 flex gap-4 text-[11px] font-semibold text-ink/55"><span>🔒 Pagamento seguro</span><span>📥 Acesso digital</span></div></div><Mockup/></div></section> }

function ProblemSection() { const items = [['⏱️','A atividade terminou antes do esperado.'],['📅','Amanhã tem aula e você ainda não preparou nada.'],['👧','Um aluno precisa de uma atividade extra.'],['🔎','Você perdeu tempo demais procurando algo adequado.']]; return <section className="bg-[#f5f7ff] px-5 py-20"><div className="mx-auto max-w-6xl"><div className="max-w-2xl"><p className="mb-3 text-xs font-black uppercase tracking-[.2em] text-coral">A rotina real de quem educa</p><h2 className="font-display text-3xl font-extrabold leading-tight sm:text-5xl">Você não precisa de mais trabalho.<br/><span className="text-purple">Precisa de uma atividade pronta.</span></h2></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{items.map(([icon,text])=><div key={text} className="rounded-3xl bg-white p-6 shadow-card transition hover:-translate-y-1"><div className="mb-5 text-3xl">{icon}</div><p className="font-bold leading-6 text-ink">{text}</p></div>)}</div><p className="mt-10 max-w-2xl text-lg font-bold text-navy">Foi para esses momentos que criamos o Kit Professora Sem Tempo™.</p></div></section> }

function SolutionFlow() { const steps=[['01','ABRA O KIT',BookOpen],['02','ESCOLHA A ATIVIDADE',Search],['03','IMPRIMA',Printer],['04','USE',Rocket]]; return <section className="px-5 py-20" id="kit"><div className="mx-auto max-w-6xl text-center"><p className="mb-3 text-xs font-black uppercase tracking-[.2em] text-purple">O mecanismo simples</p><h2 className="font-display text-3xl font-extrabold sm:text-5xl">Não complique.</h2><p className="mx-auto mt-4 max-w-xl text-ink/60">Uma biblioteca digital para resolver o inesperado com praticidade.</p><div className="mt-12 grid gap-5 md:grid-cols-4">{steps.map(([number,title,Icon],i)=><div key={title} className="relative"><div className="mx-auto mb-5 flex h-20 w-20 items-center justify-center rounded-3xl bg-navy text-white shadow-lg"><Icon size={30}/></div><span className="absolute left-1/2 top-0 -translate-x-1/2 -translate-y-3 font-display text-5xl font-extrabold text-sun/60">{number}</span><h3 className="font-display font-extrabold text-navy">{title}</h3>{i<3&&<ArrowRight className="absolute -right-3 top-8 hidden text-coral md:block"/>}</div>)}</div><p className="mt-12 text-lg font-semibold text-ink/65">Sem começar do zero. Sem procurar dezenas de links. Sem perder tempo quando você mais precisa.</p></div></section> }

function CategoriesSection() { return <section className="bg-cream px-5 py-20"><div className="mx-auto max-w-6xl"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-3 text-xs font-black uppercase tracking-[.2em] text-coral">Tudo no lugar</p><h2 className="max-w-2xl font-display text-3xl font-extrabold sm:text-5xl">Encontre o que precisa sem perder tempo.</h2></div><span className="text-5xl">📚</span></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{categories.map(([icon,title,desc])=><div key={title} className="rounded-3xl border border-ink/5 bg-white p-5 shadow-card transition hover:-translate-y-1 hover:border-purple/30"><div className="mb-5 text-3xl">{icon}</div><h3 className="font-display font-extrabold text-navy">{title}</h3><p className="mt-2 text-sm leading-6 text-ink/55">{desc}</p></div>)}</div><div className="mt-5 flex flex-col gap-5 rounded-3xl bg-navy p-7 text-white shadow-soft sm:flex-row sm:items-center sm:justify-between sm:p-10"><div><div className="mb-3 flex items-center gap-2 text-sun"><span className="text-2xl">🚨</span><span className="text-xs font-black uppercase tracking-widest">Atividades de emergência</span></div><h3 className="font-display text-2xl font-extrabold">Ainda bem que eu tenho isso salvo.</h3><p className="mt-2 text-sm text-white/65">Para aqueles momentos em que algo pronto faz toda a diferença.</p></div><Button secondary>Quero ter isso salvo</Button></div></div></section> }

function EmergencySection() { return <section className="overflow-hidden bg-purple px-5 py-20 text-white"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><div className="mb-5 text-5xl">🚨</div><h2 className="font-display text-3xl font-extrabold leading-tight sm:text-5xl">Sua gaveta de emergência pedagógica</h2><p className="mt-5 text-lg text-white/75">Para os dias em que você precisa de uma atividade agora.</p><div className="mt-8 flex items-center gap-3 text-sm font-bold text-sun"><Zap size={20}/> Você não precisa começar do zero.</div></div><div className="grid gap-3 sm:grid-cols-2">{['🕐 A atividade terminou antes.','📅 Preciso de algo para amanhã.','🏫 Surgiu uma aula extra.','📚 Um aluno precisa de atividade adicional.','🔄 O planejamento mudou.'].map(x=><div key={x} className="rounded-2xl border border-white/15 bg-white/10 p-5 font-bold backdrop-blur-sm">{x}</div>)}</div></div></section> }

function Printable({ item, i }: { item: string[]; i: number }) { const colors: Record<string,string> = { purple:'bg-purple/15 text-purple',yellow:'bg-sun/30 text-[#8a6200]',blue:'bg-navy/10 text-navy',coral:'bg-coral/15 text-coral',green:'bg-emerald-100 text-emerald-700',lavender:'bg-indigo-100 text-indigo-700' }; return <div className={`group rounded-2xl bg-white p-3 shadow-card transition hover:-translate-y-2 ${i===1||i===4?'lg:translate-y-8':''}`}><div className="aspect-[.78] rounded-xl border border-ink/10 bg-[#fffdf9] p-4"><span className={`rounded-full px-2 py-1 text-[8px] font-black ${colors[item[3]]}`}>{item[0]}</span><h3 className="mt-8 font-display text-xl font-extrabold text-navy">{item[1]}</h3><div className="mt-8 rounded-xl border-2 border-dashed border-ink/15 p-4 text-center font-display text-lg font-bold text-purple">{item[2]}</div><div className="mt-6 space-y-2"><div className="h-2 w-full rounded bg-ink/10"/><div className="h-2 w-4/5 rounded bg-ink/10"/><div className="h-2 w-3/5 rounded bg-ink/10"/></div><div className="mt-7 flex justify-between text-[9px] font-bold text-ink/30"><span>Nome: __________</span><span>♥</span></div></div></div> }
function GallerySection() { return <section id="galeria" className="bg-[#f5f7ff] px-5 py-20"><div className="mx-auto max-w-6xl"><div className="mx-auto max-w-2xl text-center"><p className="mb-3 text-xs font-black uppercase tracking-[.2em] text-coral">Prova visual</p><h2 className="font-display text-3xl font-extrabold sm:text-5xl">Veja alguns exemplos do que você vai encontrar.</h2><p className="mt-4 text-ink/60">Materiais organizados para consultar, imprimir e utilizar na rotina pedagógica.</p></div><div className="mt-12 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:gap-6">{gallery.map((item,i)=><Printable key={item[1]} item={item} i={i}/>)}</div></div></section> }

function BenefitsSection() { return <section className="px-5 py-20"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-2 lg:items-center"><div><p className="mb-3 text-xs font-black uppercase tracking-[.2em] text-purple">Mais leveza na rotina</p><h2 className="font-display text-3xl font-extrabold sm:text-5xl">O que muda na sua rotina?</h2><p className="mt-5 max-w-md leading-7 text-ink/60">Você ganha tempo, organização e segurança para lidar com aqueles momentos que não estavam no planejamento.</p></div><div className="grid gap-3 sm:grid-cols-2">{['⚡ Menos tempo procurando atividades','📚 Mais materiais organizados','🖨️ Imprima quando precisar','🚨 Tenha opções para imprevistos','📱 Acesse pelo celular, tablet ou computador','🎯 Encontre materiais por categoria'].map(x=><div key={x} className="flex items-center gap-3 rounded-2xl bg-cream p-4 font-bold text-navy"><span className="text-xl">{x.slice(0,2)}</span>{x.slice(3)}</div>)}</div></div></section> }

function BonusesSection() { const bonuses=[['🎁','50 jogos pedagógicos','R$ 19,90'],['🎁','30 atividades de emergência','R$ 14,90'],['🎁','Calendário de 30 dias','R$ 12,90'],['🎁','Capas e etiquetas','R$ 9,90']]; return <section className="bg-navy px-5 py-20 text-white"><div className="mx-auto max-w-6xl"><div className="text-center"><p className="mb-3 text-xs font-black uppercase tracking-[.2em] text-sun">Você recebe ainda mais</p><h2 className="font-display text-3xl font-extrabold sm:text-5xl">Além do kit principal, você ainda recebe:</h2></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{bonuses.map(([icon,title,price])=><div key={title} className="rounded-3xl border border-white/10 bg-white/10 p-6"><div className="text-3xl">{icon}</div><h3 className="mt-5 font-display text-lg font-extrabold">{title}</h3><div className="mt-5 text-sm text-white/50">Valor de <span className="font-bold text-white">{price}</span></div></div>)}</div><div className="mx-auto mt-10 flex max-w-md items-center justify-center gap-3 rounded-2xl bg-sun px-6 py-4 text-center font-display font-extrabold text-ink"><Gift/> Mais de R$ 57 em bônus</div></div></section> }

function OfferSection() { return <section className="bg-cream px-5 py-20"><div className="mx-auto max-w-5xl rounded-[2rem] bg-white p-7 shadow-soft sm:p-12"><div className="grid gap-10 lg:grid-cols-[1fr_.8fr] lg:items-center"><div><div className="mb-4 inline-flex rounded-full bg-sun/40 px-4 py-2 text-xs font-black uppercase text-ink">Oferta especial de acesso</div><h2 className="font-display text-3xl font-extrabold sm:text-5xl">Uma gaveta inteira de possibilidades para ter sempre à mão.</h2><div className="mt-7 grid gap-3 sm:grid-cols-2">{['Kit principal','Jogos pedagógicos','Atividades de emergência','Calendário','Capas e etiquetas'].map(x=><div key={x} className="flex items-center gap-2 text-sm font-bold"><Check size={18} className="rounded-full bg-emerald-100 p-1 text-emerald-600"/>{x}</div>)}</div></div><div className="rounded-3xl bg-navy p-7 text-center text-white"><p className="text-sm font-bold text-white/60 line-through">De R$ 47,00</p><p className="mt-2 text-sm font-bold">Hoje por apenas</p><div className="my-2 font-display text-6xl font-extrabold text-sun">R$ 27<span className="text-2xl">,00</span></div><p className="text-xs text-white/60">pagamento único</p><Button>Sim! Quero meu kit</Button><div className="mt-4 flex justify-center gap-2 text-[10px] text-white/60"><Lock size={13}/> Compra segura e acesso digital</div></div></div></div></section> }

function HowItWorks() { return <section className="px-5 py-20"><div className="mx-auto max-w-6xl text-center"><h2 className="font-display text-3xl font-extrabold sm:text-5xl">Como funciona a compra?</h2><div className="mt-12 grid gap-5 sm:grid-cols-4">{[['1','Garanta seu kit',Lock],['2','Receba o acesso',Download],['3','Escolha o material',Layers],['4','Imprima e use',Printer]].map(([n,t,I])=><div key={t} className="rounded-3xl bg-[#f5f7ff] p-6"><div className="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-2xl bg-purple font-display text-xl font-extrabold text-white">{n}</div><h3 className="font-display font-extrabold text-navy">{t}</h3></div>)}</div><p className="mt-10 font-display text-2xl font-extrabold text-coral">Simples assim.</p></div></section> }

function AudienceSection() { return <section className="bg-[#f5f7ff] px-5 py-20"><div className="mx-auto max-w-6xl text-center"><h2 className="font-display text-3xl font-extrabold sm:text-5xl">Esse kit foi feito para você?</h2><div className="mx-auto mt-10 grid max-w-4xl gap-4 sm:grid-cols-4">{[['👩🏫','Professoras'],['📚','Professores de reforço'],['🏫','Educadores'],['👨👩👧','Pais e responsáveis']].map(([i,t])=><div key={t} className="rounded-3xl bg-white p-6 shadow-card"><div className="text-4xl">{i}</div><p className="mt-4 font-bold text-navy">{t}</p></div>)}</div></div></section> }

function NotForSection() { return <section className="px-5 py-16"><div className="mx-auto max-w-4xl rounded-3xl border border-ink/10 p-7 sm:p-10"><h2 className="font-display text-2xl font-extrabold sm:text-3xl">O que este kit não é</h2><div className="mt-7 grid gap-3 sm:grid-cols-2">{['❌ Curso em vídeo','❌ Aulas particulares','❌ Material físico','❌ Planejamento automático completo'].map(x=><p key={x} className="rounded-xl bg-cream p-4 font-semibold text-ink/70">{x}</p>)}</div><p className="mt-7 leading-7 text-ink/60">Este é um acervo digital de atividades para consultar, imprimir e utilizar quando precisar.</p></div></section> }

function GuaranteeSection() { return <section className="bg-[#fff4df] px-5 py-20"><div className="mx-auto flex max-w-4xl flex-col items-center gap-7 text-center sm:flex-row sm:text-left"><div className="flex h-32 w-32 shrink-0 rotate-[-6deg] items-center justify-center rounded-full border-4 border-dashed border-coral bg-white text-center shadow-lg"><div><ShieldCheck className="mx-auto text-coral" size={30}/><div className="font-display text-xl font-extrabold text-coral">7 DIAS</div><div className="text-[9px] font-black">GARANTIA</div></div></div><div><h2 className="font-display text-3xl font-extrabold">Você tem 7 dias para conhecer o material</h2><p className="mt-4 leading-7 text-ink/65">Se dentro do prazo de garantia você entender que o Kit não é adequado para você, poderá solicitar o reembolso conforme as condições da garantia.</p></div></div></section> }

function FAQ() { const [active,setActive]=useState<number|null>(null); return <section id="duvidas" className="px-5 py-20"><div className="mx-auto max-w-3xl"><div className="text-center"><p className="mb-3 text-xs font-black uppercase tracking-[.2em] text-purple">Ainda ficou com dúvida?</p><h2 className="font-display text-3xl font-extrabold sm:text-5xl">Perguntas frequentes</h2></div><div className="mt-10 space-y-3">{faqItems.map(([q,a],i)=><div key={q} className="overflow-hidden rounded-2xl border border-ink/10 bg-white"><button onClick={()=>setActive(active===i?null:i)} className="flex w-full items-center justify-between p-5 text-left font-bold text-navy"><span>{q}</span><ChevronDown className={`transition ${active===i?'rotate-180':''}`}/></button>{active===i&&<div className="px-5 pb-5 text-sm leading-6 text-ink/60">{a}</div>}</div>)}</div></div></section> }

function FinalCTA() { return <section className="bg-navy px-5 py-20 text-center text-white"><div className="mx-auto max-w-3xl"><div className="mb-5 text-5xl">📚</div><h2 className="font-display text-3xl font-extrabold leading-tight sm:text-5xl">Da próxima vez que precisar de uma atividade, não comece uma nova busca.</h2><div className="my-8 flex flex-wrap justify-center gap-2 font-display text-lg font-extrabold text-sun sm:text-2xl"><span>ABRA.</span><span>ESCOLHA.</span><span>IMPRIMA.</span><span>USE.</span></div><p className="text-xl font-bold">Kit Professora Sem Tempo™</p><div className="my-6"><span className="mr-3 text-lg text-white/40 line-through">R$ 47,00</span><span className="font-display text-5xl font-extrabold text-sun">R$ 27,00</span></div><Button>Quero meu kit agora</Button><div className="mt-6 flex justify-center gap-4 text-xs text-white/60"><span>🔒 Compra segura</span><span>📥 Acesso digital</span><span>✅ 7 dias de garantia</span></div></div></section> }

function Footer() { return <footer className="bg-[#172653] px-5 py-8 text-center text-xs text-white/50"><p className="font-display text-base font-extrabold text-white">Kit Professora Sem Tempo™</p><p className="mt-2">Atividades prontas para os dias que pedem praticidade.</p><p className="mt-5">© 2024 • Todos os direitos reservados.</p></footer> }
function MobileStickyCTA() { return <div className="fixed bottom-0 left-0 right-0 z-50 flex items-center justify-between gap-3 border-t border-white/20 bg-navy/95 px-4 py-3 text-white shadow-2xl backdrop-blur md:hidden"><div><p className="text-[10px] font-bold text-white/70">KIT PROFESSORA SEM TEMPO™</p><p className="font-display text-xl font-extrabold text-sun">R$ 27,00</p></div><button onClick={goCheckout} className="rounded-xl bg-coral px-5 py-3 text-xs font-black uppercase text-white shadow-lg">Quero agora</button></div> }

export default function App() { return <><Header/><main><Hero/><ProblemSection/><SolutionFlow/><CategoriesSection/><EmergencySection/><GallerySection/><BenefitsSection/><BonusesSection/><OfferSection/><HowItWorks/><AudienceSection/><NotForSection/><section className="bg-[#f5f7ff] px-5 py-20"><div className="mx-auto max-w-5xl text-center"><p className="mb-3 text-xs font-black uppercase tracking-[.2em] text-coral">Materiais para usar de verdade</p><h2 className="font-display text-3xl font-extrabold sm:text-5xl">Olha o tipo de material que você poderá utilizar</h2><div className="mt-10 grid grid-cols-2 gap-4 sm:grid-cols-4">{gallery.slice(0,4).map((item,i)=><Printable key={item[1]} item={item} i={i}/>)}</div></div></section><GuaranteeSection/><FAQ/><FinalCTA/></main><Footer/><MobileStickyCTA/></> }
